### ISSUE TITLE
cp is not defined

### ISSUE THREAD

**Issue by kevinbror** [keymetrics/pm2-server-monit#59]
When I run `pm2 install pm2-server-monit` it fails. Checking the logs with `pm2 logs pm2-server-monit` shows the exception:

```
0|pm2-serv | ReferenceError: cp is not defined
0|pm2-serv |     at /Users/user/.pm2/node_modules/pm2-server-monit/lib/proc.js:12:39
0|pm2-serv |     at ChildProcess.exithandler (child_process.js:189:7)
0|pm2-serv |     at emitTwo (events.js:106:13)
0|pm2-serv |     at ChildProcess.emit (events.js:191:7)
0|pm2-serv |     at maybeClose (internal/child_process.js:920:16)
0|pm2-serv |     at Socket.<anonymous> (internal/child_process.js:351:11)
0|pm2-serv |     at emitOne (events.js:96:13)
0|pm2-serv |     at Socket.emit (events.js:188:7)
0|pm2-serv |     at Pipe._handle.close [as _onclose] (net.js:497:12)
```
Looking at the line show in the top of the stack it does indeed seem to be undefined as child_process is not required: https://github.com/pm2-hive/pm2-server-monit/blob/master/lib/proc.js#L12

**Comment by kevinbror** [comment]
Thanks!

**Comment by Unitech** [comment]
deployed

**Comment by scull7** [comment]
```sh
pm2 -v
2.10.2
```

![screenshot 2018-04-13 14 47 36](https://user-images.githubusercontent.com/234352/38759217-a1a80572-3f29-11e8-8a22-fc52e2c9e635.png)

```sh
0|pm2-serv | ReferenceError: cp is not defined
0|pm2-serv |     at /Users/nathansculli/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/lib/proc.js:12:18
0|pm2-serv |     at ChildProcess.exithandler (child_process.js:267:7)
0|pm2-serv |     at emitTwo (events.js:126:13)
0|pm2-serv |     at ChildProcess.emit (events.js:214:7)
0|pm2-serv |     at maybeClose (internal/child_process.js:925:16)
0|pm2-serv |     at Socket.stream.socket.on (internal/child_process.js:346:11)
0|pm2-serv |     at emitOne (events.js:116:13)
0|pm2-serv |     at Socket.emit (events.js:211:7)
0|pm2-serv |     at Pipe._handle.close [as _onclose] (net.js:554:12)
```

I believe this error has returned.
