### ISSUE TITLE
Cannot start in AWS Centos machine

### ISSUE THREAD

**Issue by aslabs** [keymetrics/pm2-server-monit#61]
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:362:9)
    at Object.exports.execFile (child_process.js:151:15)
    at Object.exports.exec (child_process.js:111:18)
    at module.exports (/root/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/lib/exec.js:15:6)
    at refreshMetrics (/root/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/lib/drive.js:10:3)
    at Object.init (/root/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/lib/drive.js:100:3)
    at /root/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/app.js:46:9
    at Object.PMX.initModule (/root/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/node_modules/pmx/lib/pmx.js:124:12)

**Comment by f-hj** [comment]
Hello @aslabs,
What is your NodeJS version?
Thanks
