### ISSUE TITLE
Current version is broken on MacOS. [cp is not defined]

### ISSUE THREAD

**Issue by MechanicalHuman** [keymetrics/pm2-server-monit#73]
Can you publish a new version, please? I think is also important on your side as the new command `pm2 plus` currently installs this broken package by default. 

The `package.json` file on both `development` and `master` does not reflect the current version `2.6.2`; so a pull request seems unlikely. On the bright side, the fix is already on the master branch introduced on [`cc120097 fix issue #59`](https://github.com/keymetrics/pm2-server-monit/commit/cc1200970e4fdfcaac71d185309f95a7aceb0d27)

## Module info:
- version: 2.6.2
- resolved: https://registry.npmjs.org/pm2-server-monit/-/pm2-server-monit-2.6.2.tgz

## System info:
- arch: x64
- platform: darwin
- node version: 10.7.0
- pm2 version: 3.0.3

## Error Stack:

```js
ReferenceError: cp is not defined
    at $HOME/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/lib/proc.js:12:18
    at ChildProcess.exithandler (child_process.js:282:7)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:599:12)
```

**Comment by vmarchaud** [comment]
Fixed in 3.0.0
