### ISSUE TITLE
TypeError: Cannot read property 'v1' of undefined

### ISSUE THREAD

**Issue by binarykitchen** [keymetrics/pm2-server-monit#76]
Command `pm2 module:update pm2-server-monit` causes this error:

```
/home/nodejs/.config/yarn/global/node_modules/pm2/lib/API/Modules/Modules.js:82
    if (opts.v1) {
             ^

TypeError: Cannot read property 'v1' of undefined
    at API.CLI.install (/home/nodejs/.config/yarn/global/node_modules/pm2/lib/API/Modules/Modules.js:82:14)
    at Command.<anonymous> (/home/nodejs/.config/yarn/global/node_modules/pm2/bin/pm2:497:9)
    at Command.listener (/home/nodejs/.config/yarn/global/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/home/nodejs/.config/yarn/global/node_modules/commander/index.js:651:12)
    at Command.parse (/home/nodejs/.config/yarn/global/node_modules/commander/index.js:474:21)
    at beginCommandProcessing (/home/nodejs/.config/yarn/global/node_modules/pm2/bin/pm2:157:13)
    at /home/nodejs/.config/yarn/global/node_modules/pm2/bin/pm2:231:7
```

Using PM2 version 3.0.3 here.

**Comment by vmarchaud** [comment]
I believe this issue should be in https://github.com/Unitech/pm2 not here. If you want to command `pm2 install pm2-server-monit` should works fine
