### ISSUE TITLE
TypeError: Bad argument

### ISSUE THREAD

**Issue by victorlap** [keymetrics/pm2-server-monit#79]
Hi, pm2-server-monit is erroring on our legacy server:
```
7|pm2-serv | TypeError: Bad argument
7|pm2-serv |     at TypeError (native)
7|pm2-serv |     at ChildProcess.spawn (internal/child_process.js:274:26)
7|pm2-serv |     at exports.spawn (child_process.js:362:9)
7|pm2-serv |     at Object.exports.execFile (child_process.js:151:15)
7|pm2-serv |     at Object.exports.exec (child_process.js:111:18)
7|pm2-serv |     at module.exports (/home/driver/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/src/utils/exec.js:13:23)
7|pm2-serv |     at IPNetworkMetric.fetch (/home/driver/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/src/metrics/network/ip.js:7:5)
7|pm2-serv |     at new NetworkMetrics (/home/driver/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/src/metrics/network.js:39:5)
7|pm2-serv |     at /home/driver/.pm2/modules/pm2-server-monit/node_modules/pm2-server-monit/src/index.js:50:19
7|pm2-serv |     at PMX.initModule (/usr/lib/node_modules/pm2/node_modules/@pm2/io/build/main/src/pmx.js:241:20)
```
```
$ node -v
v4.6.1
$ npm -v
2.15.9
$ pm2 -v
3.2.2
$ uname -a
Linux *****.com 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by imjeffparedes** [comment]
Having a problem with this too. Our Pm2 Plus monitoring constantly sending email notification about this.
